name: longthreads
favicon: null
layout_spectrum: 0.01395
typography_spectrum: 0.77308
title: LONG THREADS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.3125
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
